#!/bin/bash

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi
#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
# Similarly, if the wifi interface exists but no connection is active, show
# nothing

#[[ ! -d /sys/class/net/"${INTERFACE}"/wireless || \
#    "$(cat /sys/class/net/"$INTERFACE"/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

SSID=$(iwgetid | awk '{print $2}' | cut -d "\"" -f 2)
ADDR=$(ip route get 1 | awk '{print $7; exit}')

#------------------------------------------------------------------------

echo "$SSID: $ADDR" # full text
echo "$SSID: $ADDR" # short text
echo "#00FF00" # color

